#!/bin/bash
# Install Multi-Agent Cron Jobs — No sudo required
# Usage: bash scripts/install_cron_jobs.sh

echo "🤖 Installing Multi-Agent Cron Jobs"
echo "======================================"
echo ""

CRON_FILE="$HOME/.crontab"
GEMATRIA_DIR="/home/avalonas/.hermes/gematria"
CRON_LOGS_DIR="$GEMATRIA_DIR/cron_logs"

# Create logs directory if it doesn't exist
mkdir -p "$CRON_LOGS_DIR"
echo "✅ Created cron logs directory: $CRON_LOGS_DIR"
echo ""

# Display current crontab (if any)
echo "📋 Current Crontab Contents:"
echo "----------------------------"
crontab -l 2>/dev/null || echo "(No existing crontab)"
echo ""

# Save backup before installation
echo "💾 Creating backup of current crontab..."
cp "$CRON_FILE" "${CRON_FILE}.backup.$(date +%Y%m%d_%H%M%S)" 2>/dev/null || true
echo "✅ Backup saved as: $CRON_FILE.backup.*"
echo ""

# Combine overnight research and sync cron jobs
echo "🔧 Merging cron configurations..."
cat > "$CRON_FILE.tmp" << 'EOF'
# Multi-Agent System — Combined Cron Configuration
# ==============================================
# Generated by install_cron_jobs.sh
# Install with: crontab /home/avalonas/.hermes/gematria/scripts/cron_install.crontab

# ============================================
# AUTO-OBSIDIAN SYNC (Hourly)
# ============================================
0 * * * * cd /home/avalonas/.hermes/gematria && python scripts/auto_obisidian_sync_v2.py 2>&1 >> /home/avalonas/.hermes/gematria/cron_logs/hourly_sync.log

# ============================================
# PATTERN CONVERGENCE SCAN — Every 6 Hours
# ============================================
0 0,6,12,18 * * * cd /home/avalonas/.hermes/gematria && python scripts/auto_obisidian_sync_v2.py --mode convergence 2>&1 >> /home/avalonas/.hermes/gematria/cron_logs/pattern_scan.log

# ============================================
# OVERNIGHT RESEARCH PIPELINE — 3 AM DAILY
# ============================================
0 3 * * * cd /home/avalonas/.hermes/gematria && python scripts/orchestrator.py --mode overnight 2>&1 | tee /home/avalonas/.hermes/gematria/cron_logs/overnight_$(date +\%Y\%m\%d).log

# ============================================
# HEALTH CHECK — Every 30 Minutes
# ============================================
30 * * * * cd /home/avalonas/.hermes/gematria && python scripts/health_check.py 2>&1 >> /home/avalonas/.hermes/gematria/cron_logs/health_check.log

EOF

echo "✅ Combined cron configuration created"
echo ""

# Install new crontab
if [ -f "$CRON_FILE.tmp" ]; then
    echo "🚀 Installing cron jobs..."
    if crontab "$CRON_FILE.tmp"; then
        echo ""
        echo "======================================"
        echo "✅ Cron installation successful!"
        echo "======================================"
        echo ""
        echo "📋 Installed Jobs:"
        echo "  • 🕐 Hourly Sync: every hour at :00"
        echo "  • 🔍 Pattern Scan: every 6 hours (00:00, 06:00, 12:00, 18:00)"
        echo "  • 🌙 Overnight Research: daily at 3:00 AM"
        echo "  • 🏥 Health Check: every 30 minutes"
        echo ""
        echo "📁 Cron logs directory: $CRON_LOGS_DIR"
        echo "======================================"
    else
        echo "❌ Failed to install crontab. Please check for errors."
        echo "   You can edit with: crontab -e"
    fi
    rm -f "$CRON_FILE.tmp"
else
    echo "❌ No cron file created, skipping installation"
fi

echo ""
echo "📖 Next Steps:"
echo "  1. Verify cron service is running: systemctl status cron (or cron)"
echo "  2. Check logs in: $CRON_LOGS_DIR"
echo "  3. Manual override: crontab -e"
echo ""
