#!/bin/bash
# STEVE'S GEMATRIA — Quick Start Guide
# ============================================

echo ""
echo "======================================================"
echo "       🌉 STEVE'S GEMATRIA — QUICK START GUIDE         "
echo "======================================================"
echo ""
echo "📂 Base Directory: /home/avalonas/.hermes/gematria"
echo ""
echo "======================================================"
echo "     HOW TO USE MANUAL CRON ALTERNATIVES              "
echo "======================================================"
echo ""
echo "📋 OPTION 1: Source the Script (Add to .bashrc or .zshrc)"
echo ""
echo "   # Add this line to ~/.bashrc or ~/.zshrc:"
echo "   source /home/avalonas/.hermes/gematria/scripts/cron_alternatives.sh"
echo ""
echo "   Then reload your shell config:"
echo "   source ~/.bashrc      # For bash"
echo "   source ~/.zshrc       # For zsh"
echo ""
echo "======================================================"
echo "                   OR USE DIRECTLY                    "
echo "======================================================"
echo ""
echo "🚀 Run scripts directly from gematria directory:"
echo ""
echo "   cd /home/avalonas/.hermes/gematria && bash scripts/cron_alternatives.sh overnight"
echo "   cd /home/avalonas/.hermes/gematria && bash scripts/cron_alternatives.sh hourly"
echo "   cd /home/avalonas/.hermes/gematria && bash scripts/cron_alternatives.sh pattern"
echo "   cd /home/avalonas/.hermes/gematria && bash scripts/cron_alternatives.sh health"
echo ""
echo "======================================================"
echo "               EXAMPLE COMMANDS                        "
echo "======================================================"
echo ""
echo "🌙 Run overnight research pipeline:"
echo "   bash scripts/cron_alternatives.sh overnight"
echo ""
echo "🕐 Run hourly relationship sync:"
echo "   bash scripts/cron_alternatives.sh hourly"
echo ""
echo "🔍 Run pattern convergence scan:"
echo "   bash scripts/cron_alternatives.sh pattern"
echo ""
echo "💚 Run system health check:"
echo "   bash scripts/cron_alternatives.sh health"
echo ""
echo "📊 Show current system status:"
echo "   bash scripts/cron_alternatives.sh status"
echo ""
echo "📋 List all available tasks:"
echo "   bash scripts/cron_alternatives.sh list"
echo ""
echo "======================================================"
echo "           QUICK COMMAND CHEAT SHEET                   "
echo "======================================================"
echo ""
echo "   overnight  — Full research pipeline (3 AM equivalent)"
echo "   hourly     — Hourly relationship tracking sync"
echo "   pattern    — Every 6 hours pattern convergence"
echo "   health     — System integrity monitoring"
echo "   status     — Show system status and file counts"
echo "   list       — Display all available commands"
echo ""
echo "======================================================"
echo "               SOURCED AS FUNCTIONS                    "
echo "======================================================"
echo ""
echo "After sourcing the script (add to ~/.bashrc), you can use:"
echo ""
echo "   run_overnight_research()"
echo "   run_hourly_sync()"
echo "   run_pattern_scan()"
echo "   check_system_health()"
echo "   list_available_tasks()"
echo ""
echo "======================================================"
