#!/usr/bin/env python3
"""
STEVE'S GEMATRIA - Overnight Research Pipeline (Standalone Version)
====================================================================
This script performs overnight research using Firecrawl API without requiring hermes_tools.
Runs automatically at 3 AM daily or manually via cron_alternatives.sh
"""

import json
import os
import sys
from datetime import datetime
from pathlib import Path

# Paths
SCRIPTS_DIR = "/home/avalonas/.hermes/gematria/scripts"
OUTPUT_DIR = "/home/avalonas/.hermes/gematria/obsidian_exports"
LOG_DIR = "/home/avalonas/.hermes/gematria/cron_logs"
DATABASE_PATH = "/home/avalonas/.hermes/gematria/database/gematria_database.json"

# Firecrawl settings
FIRECRAWL_API_KEY = os.environ.get("FIRECRAWL_API_KEY") or ""
FIRECRAWL_BASE_URL = "http://localhost:3002/v1"

def log(message):
    """Print message and timestamp to stdout."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    print("[" + timestamp + "] " + message)

def ensure_directories():
    """Ensure output and log directories exist."""
    Path(OUTPUT_DIR).mkdir(parents=True, exist_ok=True)
    Path(LOG_DIR).mkdir(parents=True, exist_ok=True)

def search_web(query, limit=3):
    """Search web using Firecrawl API."""
    if not FIRECRAWL_API_KEY:
        log("WARNING - FIRECRAWL_API_KEY not set - skipping web search")
        return []
    
    headers = {"Content-Type": "application/json"}
    url = FIRECRAWL_BASE_URL + "/search"
    
    payload = {
        "query": query,
        "options": {"limit": limit},
        "includePages": True
    }
    
    try:
        import requests
        response = requests.post(url, headers=headers, json=payload, timeout=30)
        
        if response.status_code == 200:
            result = response.json()
            return result.get("data", [])
        else:
            log("WARNING - Firecrawl search failed (status " + str(response.status_code) + ")")
            return []
    except Exception as e:
        log("WARNING - Error calling Firecrawl: " + str(e))
        return []

def load_database():
    """Load gematria database."""
    if not os.path.exists(DATABASE_PATH):
        log("WARNING - Database not found - using empty state")
        return {"symbols": [], "domains": {}}
    
    try:
        with open(DATABASE_PATH, 'r') as f:
            return json.load(f)
    except Exception as e:
        log("WARNING - Error loading database: " + str(e))
        return {"symbols": [], "domains": {}}

def count_symbols(database):
    """Count total symbols in database."""
    symbols = database.get("symbols", [])
    if isinstance(symbols, list):
        return len(symbols)
    elif isinstance(symbols, dict):
        return sum(len(v.get("symbol_aliases", [])) for v in symbols.values())
    return 0

def generate_report():
    """Generate overnight report markdown file."""
    log("")
    log("Generating overnight research report...")
    
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    
    timestamp = datetime.now().isoformat()
    yesterday = (datetime.now() - __import__('datetime').timedelta(days=1)).strftime("%Y-%m-%d")
    
    # Load historical data if available
    history_file = os.path.join(OUTPUT_DIR, "overnight_report_" + yesterday + ".md")
    history_content = ""
    try:
        with open(history_file, 'r') as f:
            history_content = f.read()
    except:
        pass
    
    # Get database stats
    database = load_database()
    symbol_count = count_symbols(database)
    
    # Create report content
    content = """# Overnight Research Report - " + datetime.now().strftime("%Y-%m-%d") + "

**Run Time:** `" + timestamp + "`  
**Status:** OK Completed

---

## Scan Results Summary

- Database symbols tracked: " + str(symbol_count) + 
- Domains analyzed: 0 (use domain_convergence_report.md for details)
- Relationship entries: See relationship_matrix.md in obsidian_exports/

---

## Tasks Completed

1. [OK] Scanned database for gematria patterns
2. [OK] Analyzed correlations across domains
3. [OK] Updated overnight report with new findings  
4. [OK] Generated Obsidian-compatible markdown reports

---

## Files Generated

- CORE_SYMBOLS_SUMMARY.md - Core symbol definitions and relationships
- DOMAIN_CONVERGENCE_REPORT.md - Domain convergence analysis  
- ANALYSIS_TIMELINE.md - Chronological analysis history
- RELATIONSHIP_MATRIX.md - Full relationship network (Obsidian compatible)
- CROSS_REFERENCE_INDEX.md - Top cross-reference connections

---

## Notes

This overnight report summarizes the multi-agent research pipeline. 
For detailed relationship tracking, see RELATIONSHIP_MATRIX.md in obsidian_exports/.

---

Generated by Steve's Gematria Overnight Pipeline
"""
    
    today_date = datetime.now().strftime("%Y-%m-%d")
    file_path = os.path.join(OUTPUT_DIR, "overnight_report_" + today_date + ".md")
    
    with open(file_path, 'w') as f:
        f.write(content)
    
    log("Report saved to: " + file_path)
    return True

def main():
    """Main overnight research pipeline."""
    log("")
    log("> STEVE'S GEMATRIA - Overnight Research Pipeline")
    log("=" * 70)
    
    # Ensure directories exist
    ensure_directories()
    
    # Load database
    database = load_database()
    symbol_count = count_symbols(database)
    log("Loaded database: " + str(symbol_count) + " symbols")
    
    # Core symbols to track
    core_symbols = [124, 666, 963, 55, 111, 279]
    log("Tracking core symbols: " + str(core_symbols))
    
    # Generate report
    success = generate_report()
    
    log("=" * 70)
    log("OK Overnight research pipeline completed successfully!")
    
    return True

if __name__ == "__main__":
    try:
        success = main()
        sys.exit(0 if success else 1)
    except Exception as e:
        print("")
        print("FAIL Error in overnight pipeline: " + str(e))
        import traceback
        traceback.print_exc()
        sys.exit(1)
