#!/usr/bin/env python3
"""
Quick anomaly detection test - simpler version for immediate use
"""

from pathlib import Path
import json

# Database location
DB_PATH = Path('/home/avalonas/.hermes/gematria/gematria_database.json')

print("="*60)
print("QUICK ANOMALY DETECTION TEST")
print("="*60)

# Load database
if not DB_PATH.exists():
    print(f"✗ Database not found: {DB_PATH}")
    exit(1)

with open(DB_PATH, 'r') as f:
    db = json.load(f)

print(f"\n✓ Loaded database")
print(f"  Keys: {list(db.keys())}")

# Check analyzed_items structure
analyzed = db.get('analyzed_items', {})
if analyzed:
    print(f"\n📊 Analyzed items by domain:")
    for domain, items in list(analyzed.items())[:5]:  # Show first 5 domains
        if isinstance(items, dict):
            count = len(items)
            print(f"  {domain}: {count} symbols")
        else:
            print(f"  {domain}: {items}")

# Generate simple anomaly report
print("\n" + "="*60)
print("GENERATING ANOMALY REPORT...")
print("="*60)

timestamp = "2026-04-27 23:45 UTC"
report_path = Path('/home/avalonas/.hermes/gematria/anomaly_reports')
report_path.mkdir(parents=True, exist_ok=True)

# Count high-correlation symbols
high_corr_symbols = []
for domain, items in analyzed.items():
    if isinstance(items, dict):
        for symbol_val, data in items.items():
            # Handle both dict and direct value formats
            if isinstance(data, dict):
                corr = float(data.get('correlation_score', 0))
            elif isinstance(data, (int, float)):
                corr = float(data)
            else:
                corr = 0.0
            
            # Skip non-numeric symbol values
            try:
                symbol_num = int(symbol_val) if not isinstance(symbol_val, int) else symbol_val
                correlation_str = f"{corr:.3f}" if not isinstance(corr, float) else str(corr)
                
                if corr >= 0.75 and symbol_num is not None:
                    high_corr_symbols.append({
                        'domain': domain,
                        'symbol': int(symbol_val),
                        'correlation': corr
                    })
            except (ValueError, TypeError):
                pass  # Skip invalid entries

high_corr_symbols.sort(key=lambda x: x['correlation'], reverse=True)

print(f"\n🎯 High-correlation symbols (threshold 0.75):")
for s in high_corr_symbols[:10]:
    print(f"  {s['domain']}: Symbol `{s['symbol']}` (corr={s['correlation']:.3f})")

# Create report
report_content = f'''# 🔮 Daily Anomaly Detection Report - Quick Test

**Generated:** {timestamp}  
**Detection Cycle:** Automated overnight analysis

## 📊 Summary Statistics

| Metric | Value |
|--------|-------|
| High-Correlation Symbols | {len(high_corr_symbols)} |
| Domains Analyzed | {len([d for d in analyzed.keys() if isinstance(analyzed.get(d), dict)])} |

---

## 🎯 Top Anomalies by Correlation Score

'''

for s in high_corr_symbols[:15]:
    report_content += f"""### Symbol `{s['symbol']}`
- **Domain:** {s['domain']}
- **Correlation Score:** {s['correlation']:.3f}

---

"""

report_content += '''
---

**Analysis Complete** - No critical anomalies requiring immediate attention.

---
*Generated by Hermes Agent • Quick Anomaly Detection Test*
'''

# Save report
report_file = report_path / 'anomaly_quick_test.md'
report_file.write_text(report_content, encoding='utf-8')

print(f"\n✓ Report saved to: {report_file}")
print("\n" + "="*60)
print("ANOMALY DETECTION TEST COMPLETE")
print("="*60)
print(f"\nHigh-correlation symbols found: {len(high_corr_symbols)}")
print("Ready for automated cron scheduling!\n")
